// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/aws_email.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	protos/aws_email.proto
	protos/developer.proto
	protos/token.proto

It has these top-level messages:
	EmailRequest
	EmailResponse
	GenToekenRequest
	GenTokenResponse
	CheckToekenRequest
	CheckTokenResponse
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailRequest struct {
	From     string   `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To       string   `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Cc       []string `protobuf:"bytes,3,rep,name=cc" json:"cc,omitempty"`
	Subject  string   `protobuf:"bytes,4,opt,name=subject" json:"subject,omitempty"`
	Charset  string   `protobuf:"bytes,5,opt,name=charset" json:"charset,omitempty"`
	TextBody string   `protobuf:"bytes,6,opt,name=textBody" json:"textBody,omitempty"`
	HtmlBody string   `protobuf:"bytes,7,opt,name=htmlBody" json:"htmlBody,omitempty"`
}

func (m *EmailRequest) Reset()                    { *m = EmailRequest{} }
func (m *EmailRequest) String() string            { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()               {}
func (*EmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmailRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EmailRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EmailRequest) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetCharset() string {
	if m != nil {
		return m.Charset
	}
	return ""
}

func (m *EmailRequest) GetTextBody() string {
	if m != nil {
		return m.TextBody
	}
	return ""
}

func (m *EmailRequest) GetHtmlBody() string {
	if m != nil {
		return m.HtmlBody
	}
	return ""
}

type EmailResponse struct {
	MessageId string `protobuf:"bytes,1,opt,name=messageId" json:"messageId,omitempty"`
}

func (m *EmailResponse) Reset()                    { *m = EmailResponse{} }
func (m *EmailResponse) String() string            { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()               {}
func (*EmailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EmailResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailRequest)(nil), "protos.EmailRequest")
	proto.RegisterType((*EmailResponse)(nil), "protos.EmailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EmailService service

type EmailServiceClient interface {
	// 发送邮件
	SendMail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type emailServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailServiceClient(cc *grpc.ClientConn) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendMail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := grpc.Invoke(ctx, "/protos.EmailService/SendMail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EmailService service

type EmailServiceServer interface {
	// 发送邮件
	SendMail(context.Context, *EmailRequest) (*EmailResponse, error)
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EmailService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendMail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMail",
			Handler:    _EmailService_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/aws_email.proto",
}

func init() { proto.RegisterFile("protos/aws_email.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x49, 0x5a, 0xfa, 0x18, 0x01, 0x12, 0x16, 0x20, 0xab, 0x62, 0x51, 0xb2, 0x62, 0x43,
	0x90, 0x60, 0xc5, 0x36, 0x12, 0x8b, 0x2e, 0xd8, 0xb4, 0x1f, 0x80, 0x5c, 0x67, 0xa0, 0x81, 0xb8,
	0x0e, 0x9e, 0x09, 0x8f, 0x9f, 0xe2, 0x1b, 0x91, 0xed, 0x84, 0xd7, 0xce, 0xf7, 0x9c, 0x91, 0x3d,
	0xbe, 0x70, 0xd2, 0x38, 0xcb, 0x96, 0x2e, 0xd5, 0x1b, 0xdd, 0xa3, 0x51, 0x55, 0x9d, 0x07, 0x20,
	0x46, 0x91, 0x67, 0x9f, 0x09, 0xec, 0xdd, 0x7a, 0xbe, 0xc4, 0x97, 0x16, 0x89, 0x85, 0x80, 0xe1,
	0x83, 0xb3, 0x46, 0x26, 0xf3, 0xe4, 0x7c, 0xba, 0x0c, 0x67, 0x71, 0x00, 0x29, 0x5b, 0x99, 0x06,
	0x92, 0xb2, 0xf5, 0x59, 0x6b, 0x39, 0x98, 0x0f, 0x7c, 0xd6, 0x5a, 0x48, 0x18, 0x53, 0xbb, 0x7e,
	0x42, 0xcd, 0x72, 0x18, 0x86, 0xfa, 0xe8, 0x8d, 0xde, 0x28, 0x47, 0xc8, 0x72, 0x37, 0x9a, 0x2e,
	0x8a, 0x19, 0x4c, 0x18, 0xdf, 0xb9, 0xb0, 0xe5, 0x87, 0x1c, 0x05, 0xf5, 0x9d, 0xbd, 0xdb, 0xb0,
	0xa9, 0x83, 0x1b, 0x47, 0xd7, 0xe7, 0xec, 0x02, 0xf6, 0xbb, 0x7d, 0xa9, 0xb1, 0x5b, 0x42, 0x71,
	0x0a, 0x53, 0x83, 0x44, 0xea, 0x11, 0x17, 0x65, 0xb7, 0xf5, 0x0f, 0xb8, 0x5a, 0x74, 0xdf, 0x5b,
	0xa1, 0x7b, 0xad, 0x34, 0x8a, 0x1b, 0x98, 0xac, 0x70, 0x5b, 0xde, 0xa9, 0xaa, 0x16, 0x47, 0xb1,
	0x0b, 0xca, 0x7f, 0x17, 0x30, 0x3b, 0xfe, 0x47, 0xe3, 0x33, 0xd9, 0x4e, 0x71, 0x06, 0x87, 0xda,
	0x9a, 0x5c, 0x35, 0xcf, 0x4d, 0xeb, 0x30, 0x4e, 0x15, 0x7f, 0x6e, 0x5f, 0xc7, 0x56, 0xaf, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0x9c, 0x8e, 0xf0, 0x76, 0x01, 0x00, 0x00,
}
