// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/developer.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DeveloperService service

type DeveloperServiceClient interface {
	GenAccessToken(ctx context.Context, in *GenToekenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error)
	CheckToken(ctx context.Context, in *CheckToekenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
	// 发送邮件
	SendMail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	// 站内信 API CURD
	MessgeCreate(ctx context.Context, in *Messge, opts ...grpc.CallOption) (*MessgeResponse, error)
	MessgeUpdate(ctx context.Context, in *Messge, opts ...grpc.CallOption) (*Messge, error)
	MessgeRead(ctx context.Context, in *MessgeReadRequest, opts ...grpc.CallOption) (*MessgeListResponse, error)
	MessgeDelete(ctx context.Context, in *MessgeDeleteRequest, opts ...grpc.CallOption) (*MessgeResponse, error)
}

type developerServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeveloperServiceClient(cc *grpc.ClientConn) DeveloperServiceClient {
	return &developerServiceClient{cc}
}

func (c *developerServiceClient) GenAccessToken(ctx context.Context, in *GenToekenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error) {
	out := new(GenTokenResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/GenAccessToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) CheckToken(ctx context.Context, in *CheckToekenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	out := new(CheckTokenResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/CheckToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) SendMail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/SendMail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) MessgeCreate(ctx context.Context, in *Messge, opts ...grpc.CallOption) (*MessgeResponse, error) {
	out := new(MessgeResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/MessgeCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) MessgeUpdate(ctx context.Context, in *Messge, opts ...grpc.CallOption) (*Messge, error) {
	out := new(Messge)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/MessgeUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) MessgeRead(ctx context.Context, in *MessgeReadRequest, opts ...grpc.CallOption) (*MessgeListResponse, error) {
	out := new(MessgeListResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/MessgeRead", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) MessgeDelete(ctx context.Context, in *MessgeDeleteRequest, opts ...grpc.CallOption) (*MessgeResponse, error) {
	out := new(MessgeResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/MessgeDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeveloperService service

type DeveloperServiceServer interface {
	GenAccessToken(context.Context, *GenToekenRequest) (*GenTokenResponse, error)
	CheckToken(context.Context, *CheckToekenRequest) (*CheckTokenResponse, error)
	// 发送邮件
	SendMail(context.Context, *EmailRequest) (*EmailResponse, error)
	// 站内信 API CURD
	MessgeCreate(context.Context, *Messge) (*MessgeResponse, error)
	MessgeUpdate(context.Context, *Messge) (*Messge, error)
	MessgeRead(context.Context, *MessgeReadRequest) (*MessgeListResponse, error)
	MessgeDelete(context.Context, *MessgeDeleteRequest) (*MessgeResponse, error)
}

func RegisterDeveloperServiceServer(s *grpc.Server, srv DeveloperServiceServer) {
	s.RegisterService(&_DeveloperService_serviceDesc, srv)
}

func _DeveloperService_GenAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenToekenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).GenAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/GenAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).GenAccessToken(ctx, req.(*GenToekenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckToekenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).CheckToken(ctx, req.(*CheckToekenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).SendMail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_MessgeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Messge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).MessgeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/MessgeCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).MessgeCreate(ctx, req.(*Messge))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_MessgeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Messge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).MessgeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/MessgeUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).MessgeUpdate(ctx, req.(*Messge))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_MessgeRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessgeReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).MessgeRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/MessgeRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).MessgeRead(ctx, req.(*MessgeReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_MessgeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessgeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).MessgeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/MessgeDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).MessgeDelete(ctx, req.(*MessgeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeveloperService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DeveloperService",
	HandlerType: (*DeveloperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenAccessToken",
			Handler:    _DeveloperService_GenAccessToken_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _DeveloperService_CheckToken_Handler,
		},
		{
			MethodName: "SendMail",
			Handler:    _DeveloperService_SendMail_Handler,
		},
		{
			MethodName: "MessgeCreate",
			Handler:    _DeveloperService_MessgeCreate_Handler,
		},
		{
			MethodName: "MessgeUpdate",
			Handler:    _DeveloperService_MessgeUpdate_Handler,
		},
		{
			MethodName: "MessgeRead",
			Handler:    _DeveloperService_MessgeRead_Handler,
		},
		{
			MethodName: "MessgeDelete",
			Handler:    _DeveloperService_MessgeDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/developer.proto",
}

func init() { proto.RegisterFile("protos/developer.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x0b, 0x2f, 0xbc, 0xc8, 0x22, 0x45, 0x97, 0x5a, 0x34, 0xde, 0x0a, 0x5e, 0xa3, 0xe8,
	0x45, 0x8f, 0xb6, 0x4d, 0x7b, 0xb1, 0x17, 0x5b, 0xcf, 0xb2, 0x26, 0x0f, 0x35, 0x24, 0xd9, 0x5d,
	0x33, 0xdb, 0xfa, 0x51, 0xfd, 0x3a, 0xd2, 0xee, 0x8e, 0x24, 0xa9, 0x1e, 0xf7, 0xf7, 0xfc, 0x99,
	0x0c, 0x13, 0x31, 0xb4, 0xb5, 0x71, 0x86, 0xae, 0x33, 0x6c, 0x51, 0x1a, 0x8b, 0x3a, 0xde, 0x03,
	0xf9, 0xdf, 0xf3, 0x48, 0x06, 0xdd, 0x99, 0x02, 0xda, 0x6b, 0x11, 0x67, 0xd4, 0x27, 0xbd, 0xa2,
	0x52, 0x79, 0x19, 0xf8, 0x20, 0xf0, 0x0a, 0x44, 0x6a, 0x0d, 0x4f, 0x6f, 0xbf, 0xfe, 0x89, 0x93,
	0x29, 0xb7, 0x2f, 0x51, 0x6f, 0xf3, 0x14, 0x72, 0x26, 0xfa, 0x73, 0xe8, 0xc7, 0x34, 0x05, 0xd1,
	0x6a, 0x57, 0x2d, 0xcf, 0xbd, 0x9d, 0xe2, 0x39, 0xf4, 0xca, 0xa0, 0x80, 0x7e, 0xc6, 0xc7, 0x06,
	0xe4, 0xa2, 0xb6, 0xb2, 0x17, 0xc8, 0x1a, 0x4d, 0x18, 0xf5, 0xe4, 0x4c, 0x88, 0xc9, 0x3b, 0xd2,
	0xc2, 0x77, 0x44, 0xec, 0x0c, 0xac, 0xd9, 0xd2, 0xd5, 0xda, 0x3d, 0x0f, 0xe2, 0x68, 0x09, 0x9d,
	0x2d, 0x54, 0x5e, 0xca, 0x01, 0x3b, 0x93, 0xdd, 0x6e, 0x9c, 0x3f, 0xeb, 0xd0, 0x9f, 0xe8, 0xbd,
	0x38, 0x5e, 0x80, 0x68, 0x8d, 0x49, 0x0d, 0xe5, 0x20, 0xfb, 0x6c, 0xf4, 0x34, 0x1a, 0xb6, 0xdf,
	0x8d, 0xe4, 0x0d, 0x27, 0x5f, 0x6c, 0xf6, 0x5b, 0xb2, 0xf3, 0x1e, 0xf5, 0x64, 0x22, 0x04, 0xb7,
	0xa8, 0x4c, 0x5e, 0x74, 0x9b, 0x55, 0x76, 0xb0, 0xad, 0x97, 0x9e, 0x72, 0x72, 0x8d, 0xc1, 0x09,
	0x0f, 0x9e, 0xa2, 0x84, 0x83, 0xbc, 0x6c, 0xbb, 0x3d, 0xe5, 0xaa, 0x3f, 0xbf, 0x7f, 0x7c, 0x25,
	0x4e, 0x53, 0x53, 0xc5, 0xca, 0x16, 0x76, 0x53, 0x87, 0x73, 0x8f, 0x0f, 0x6e, 0xfd, 0xe6, 0x7f,
	0xa5, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xd3, 0xc9, 0xcc, 0x6b, 0x02, 0x00, 0x00,
}
