// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/developer.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DeveloperService service

type DeveloperServiceClient interface {
	GenAccessToken(ctx context.Context, in *GenToekenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error)
	CheckToken(ctx context.Context, in *CheckToekenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
	// 发送邮件
	SendMail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type developerServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeveloperServiceClient(cc *grpc.ClientConn) DeveloperServiceClient {
	return &developerServiceClient{cc}
}

func (c *developerServiceClient) GenAccessToken(ctx context.Context, in *GenToekenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error) {
	out := new(GenTokenResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/GenAccessToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) CheckToken(ctx context.Context, in *CheckToekenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	out := new(CheckTokenResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/CheckToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) SendMail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := grpc.Invoke(ctx, "/protos.DeveloperService/SendMail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeveloperService service

type DeveloperServiceServer interface {
	GenAccessToken(context.Context, *GenToekenRequest) (*GenTokenResponse, error)
	CheckToken(context.Context, *CheckToekenRequest) (*CheckTokenResponse, error)
	// 发送邮件
	SendMail(context.Context, *EmailRequest) (*EmailResponse, error)
}

func RegisterDeveloperServiceServer(s *grpc.Server, srv DeveloperServiceServer) {
	s.RegisterService(&_DeveloperService_serviceDesc, srv)
}

func _DeveloperService_GenAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenToekenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).GenAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/GenAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).GenAccessToken(ctx, req.(*GenToekenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckToekenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).CheckToken(ctx, req.(*CheckToekenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeveloperService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).SendMail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeveloperService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DeveloperService",
	HandlerType: (*DeveloperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenAccessToken",
			Handler:    _DeveloperService_GenAccessToken_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _DeveloperService_CheckToken_Handler,
		},
		{
			MethodName: "SendMail",
			Handler:    _DeveloperService_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/developer.proto",
}

func init() { proto.RegisterFile("protos/developer.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0xf5, 0x22, 0x92, 0x83, 0x68, 0x50, 0x91, 0x1c, 0x05, 0xaf, 0x15, 0xf4, 0xe4, 0xd1,
	0xaa, 0xed, 0xc9, 0x8b, 0xed, 0x5d, 0xb2, 0xe9, 0xc0, 0x96, 0xb4, 0x49, 0x36, 0xaf, 0xed, 0xfe,
	0xda, 0xfd, 0x2f, 0x4b, 0x9b, 0x06, 0xb6, 0xdd, 0xeb, 0x7c, 0x33, 0x1f, 0xbc, 0xc7, 0x1e, 0x9d,
	0xb7, 0x9d, 0xa5, 0xd7, 0x0a, 0x03, 0x1a, 0xeb, 0xe0, 0x93, 0x29, 0xe0, 0x57, 0x21, 0x17, 0x7c,
	0xe6, 0x9d, 0xd5, 0x30, 0x81, 0x89, 0xb8, 0x91, 0x7b, 0xfa, 0x47, 0x2b, 0xeb, 0x26, 0xe4, 0x6f,
	0x87, 0x4b, 0x76, 0xfb, 0x1d, 0x3d, 0x05, 0xfc, 0x50, 0x2b, 0xf0, 0x8c, 0xdd, 0xe4, 0x30, 0x9f,
	0x4a, 0x81, 0xa8, 0x1c, 0x25, 0xfc, 0x29, 0xd4, 0x29, 0xc9, 0x61, 0x4a, 0x0b, 0x0d, 0xf3, 0x87,
	0x5d, 0x0f, 0xea, 0xc4, 0x92, 0x4c, 0x80, 0x9c, 0x35, 0x84, 0xe7, 0x0b, 0x9e, 0x31, 0xf6, 0xb5,
	0x85, 0xd2, 0xc1, 0x21, 0x62, 0x73, 0xce, 0x4e, 0x2d, 0x6b, 0xb6, 0xf4, 0x7c, 0xb0, 0xeb, 0x02,
	0xa6, 0xfa, 0x95, 0x75, 0xc3, 0xef, 0x63, 0xf3, 0x67, 0xbc, 0x22, 0xee, 0x1f, 0x56, 0x69, 0x9c,
	0xa6, 0x2f, 0xec, 0x4e, 0xd9, 0x36, 0x91, 0x4e, 0xbb, 0xde, 0x23, 0xb4, 0xd2, 0xb3, 0x8b, 0x37,
	0xe1, 0x75, 0xef, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x4d, 0x3b, 0x9e, 0x5b, 0x01, 0x00,
	0x00,
}
