appname: bmsg
httpport: 4008
runmode: prod
autorender: false
copyrequestbody: true
grpclisten: :4008
pgdatasource: user=postgres password=postgres dbname=test host=127.0.0.1 port=5432
  sslmode=disable
ormdebug: true
enabledocs: true
loglevel: 7
